td_api_baseurl: https://api.treasuredata.com
cdp_api_baseurl: https://api-cdp.treasuredata.com

target:
  database: account_reporting
  tables:
    activations_list: activations
    queries_list: queries

reports_to_run:
  activations_list: true
  queries_list: true