# Name of database where model will read and write data to.
in_db: mta_sample

# Enter name of a touchpoints table. `queries/shuffle.sql` enriches the table
# with an `ab_rnd` attribute.
in_table: touchpoints

# This points to the column that contains unique user IDs, most commonly
# 'canonical_id' since this is typically the output of our ID unification
# algorithm.
unique_id: user_id

# Name of the column that contains timestamp for each touchpoint.
time_col: time

# This tells LSTM model to use that column as the categorical features when
# predicting probabilities of conversion. In other words - this is the column
# that you are trying to get the final shapely values for.
source_col: source

# Name of the column that marks conversion events.
conversion_col: conversion

# Lookback window you want to set before the model starts to define how many
# days from conversion events do you want to track back to define what
# marketing touchpoints were part of the user journey.
lookback_window_days: 3
