[tool.poetry]
name = "pyscript"
version = "0.1.0"
description = ""
authors = ["kyoshi <kazunori.yoshimura@treasure-data.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"